# Generated by Django 5.2.4 on 2025-08-24 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable public UUID identifier.', primary_key=True, serialize=False, verbose_name='public id')),
                ('resume_snapshot', models.FileField(blank=True, help_text='Optional resume copy uploaded specifically for this application.', null=True, upload_to='applications/%Y/%m/')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer extended'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=20)),
                ('applicant', models.ForeignKey(help_text='User who submitted the application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('job', models.ForeignKey(help_text='Job being applied for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='job')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable public UUID identifier.', primary_key=True, serialize=False, verbose_name='public id')),
                ('event', models.CharField(help_text='e.g., Status changed, Note added', max_length=80)),
                ('note', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application')),
            ],
            options={
                'verbose_name': 'application event',
                'verbose_name_plural': 'application events',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='app_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'created_at'], name='app_applicant_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_job_applicant'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', 'created_at'], name='appevent_app_created_idx'),
        ),
    ]
